services:
  vpnclient_115_124_61_232_1974:
    cap_add:
    - ALL
    container_name: vpnclient_115_124_61_232_1974
    environment:
      VPN_HOST: 115.124.61.232
      VPN_HUB: VPNGATE
      VPN_NAME: vpn1
      VPN_NIC_MAC: db:e0:14:72:8f:69
      VPN_PASSWORD: vpn
      VPN_PORT: 1974
      VPN_PORTOCOL: tcp
      VPN_USER: vpn
    image: aron666/softether-vpnclient
    network_mode: vpn
    privileged: true
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /dev:/dev
    - /lib/modules:/lib/modules
version: '3'
